# Generated by Django 5.2 on 2025-04-28 12:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachings', '0002_alter_teachingpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('embed', 3), ('document', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'max_height': 400, 'max_width': 800}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}),
        ),
    ]
