# Generated by Django 5.2 on 2025-04-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypage',
            name='intro',
            field=models.CharField(blank=True, help_text='Short introduction text to display on cards and previews.', max_length=300),
        ),
    ]
