# Generated by Django 5.2 on 2025-04-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teachings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this user has access to.', related_name='users', to='teachings.category'),
        ),
    ]
