# Generated by Django 5.2 on 2025-04-26 20:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_quote', models.CharField(blank=True, help_text='Short inspirational quote to overlay on the hero image.', max_length=255)),
                ('intro_body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('embed_video', 2), ('image', 3), ('gallery', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'bold', 'italic', 'link']}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {})}, null=True)),
                ('featured_activity_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.activitypage')),
                ('featured_activity_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.activitypage')),
                ('featured_activity_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.activitypage')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
