# Generated by Django 5.2 on 2025-04-19 13:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_activity_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.activitypage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_activity_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.activitypage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_activity_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.activitypage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_quote',
            field=models.CharField(blank=True, help_text='Short inspirational quote to overlay on the hero image.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
