# Generated by Django 5.2 on 2025-04-19 14:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_featured_activity_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='intro_body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('embed_video', 2), ('image', 3), ('gallery', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'bold', 'italic', 'link']}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {})}, null=True),
        ),
    ]
