# Generated by Django 5.2 on 2025-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
