# Generated by Django 5.1.8 on 2025-06-01 12:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='A unique identifier used in URLs and code.', max_length=255, unique=True)),
                ('practice_type', models.CharField(choices=[('collective_accumulation', 'Collective Accumulation'), ('practice', 'Practice')], default='practice', help_text='The type of practice.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the practice.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this from users selecting new practices.')),
            ],
            options={
                'verbose_name': 'Practice Definition',
                'verbose_name_plural': 'Practice Definitions',
                'ordering': ['practice_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='User can archive activities they no longer track.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trackers', to='tracker.practicedefinition', verbose_name='Practice Definition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Tracked Practice',
                'verbose_name_plural': 'User Tracked Practices',
                'ordering': ['user', 'definition__practice_type', 'definition__name'],
                'unique_together': {('user', 'definition')},
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malas_submitted', models.IntegerField(blank=True, help_text='Number of malas completed (integer).', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Malas Submitted')),
                ('time_submitted_hours', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Time: Hours')),
                ('time_submitted_minutes', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Time: Minutes')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Activity')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='tracker.useractivity', verbose_name='Tracked Practice')),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
