# Generated by Django 5.1.8 on 2025-05-03 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='A unique identifier used in URLs and code.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('allow_user_defined_activities', models.BooleanField(default=True, help_text='Can users add their own named activities within this type?')),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='A unique identifier used in URLs and code.', max_length=255, unique=True)),
                ('unit_name', models.CharField(default='repetitions', help_text="The name of the unit being counted (e.g., 'malas', 'mantras', 'minutes', 'sessions').", max_length=50)),
                ('unit_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Factor to convert submitted quantity to a base value (e.g., 108 for malas converting to mantras). Use 1 if no conversion needed.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this from users selecting new activities.')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_definitions', to='tracker.activitytype')),
            ],
            options={
                'verbose_name': 'Predefined Activity',
                'verbose_name_plural': 'Predefined Activities',
                'ordering': ['activity_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=255, verbose_name='Custom Activity Name')),
                ('is_active', models.BooleanField(default=True, help_text='User can archive activities they no longer track.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_activities', to='tracker.activitytype', verbose_name='Activity Type')),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_trackers', to='tracker.activitydefinition', verbose_name='Predefined Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Tracked Activity',
                'verbose_name_plural': 'User Tracked Activities',
                'ordering': ['user', 'activity_type', 'definition__name', 'custom_name'],
                'unique_together': {('user', 'activity_type', 'custom_name'), ('user', 'definition')},
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_submitted', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantity Submitted')),
                ('calculated_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15, verbose_name='Calculated Total')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Activity')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='tracker.useractivity', verbose_name='Tracked Activity')),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
