# Generated by Django 5.1.8 on 2025-06-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='allow_user_defined_activities',
            field=models.BooleanField(default=False, help_text='Can users add their own named activities within this type?'),
        ),
    ]
