# Generated by Django 5.1.8 on 2025-06-01 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_activitytype_allow_user_defined_activities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['user', 'activity_type', 'definition__name'], 'verbose_name': 'User Tracked Activity', 'verbose_name_plural': 'User Tracked Activities'},
        ),
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together={('user', 'definition')},
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='allow_user_defined_activities',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='custom_name',
        ),
    ]
